language: php

php: [5.3.3, 5.3, 5.4, 5.5, 5.6, hhvm]

env:
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*

matrix:
  allow_failures:
  - php: hhvm

before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle=$SYMFONY_VERSION; composer require --no-update symfony/twig-bundle=$SYMFONY_VERSION; fi;'
  - composer require --no-update satooshi/php-coveralls=dev-master
  - composer install --dev --prefer-source
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

cache:
  directories:
  - $HOME/.composer/
