parameters:
  boekkooi.twigjack.defer.extension.class: Boekkooi\Bundle\TwigJackBundle\Twig\Extension\DeferExtension

services:
  # defer extension
  boekkooi.twigjack.defer.extension:
    class: %boekkooi.twigjack.defer.extension.class%
    tags:
      - { name: "twig.extension" }
