parameters:
  boekkooi.twig_jack.defer.extension.class: Boekkooi\Bundle\TwigJackBundle\Twig\Extension\DeferExtension

services:
  # defer extension
  boekkooi.twig_jack.defer.extension:
    class: %boekkooi.twig_jack.defer.extension.class%
    arguments: [ %boekkooi.twig_jack.defer.prefix% ]
    tags:
      - { name: "twig.extension" }
